insert into acl.superadmin_emails (email) values
  ('admin@example.com'),
  ('wojciech.majewski@pm.me')
  on conflict do nothing;

insert into feed.notes (content) values
  ('Politics | Mr. President, we have to stop the police!'),
  ('Health | Brush your tooths twice a day'),
  ('Travel | I have to go to Canada!'),
  ('Food | Best recipe for the week:'),
  ('Sport | In the last match our team won!')
  on conflict do nothing;

---------------------------- import github stars -----------------------------------
insert into feed.notes (content) values
('Starred GitHub repo: jackc/tern - The SQL Fan''s Migrator'),
('Starred GitHub repo: pngwn/MDsveX - A markdown preprocessor for Svelte.'),
('Starred GitHub repo: peterfajdiga/kwin4_effect_geometry_change - A KWin animation for windows moved or resized by programs or scripts'),
('Starred GitHub repo: commitizen/cz-cli - The commitizen command line utility. #BlackLivesMatter'),
('Starred GitHub repo: tmux-plugins/tmux-sensible - basic tmux settings everyone can agree on'),
('Starred GitHub repo: jaclu/tmux-power-zoom - Zoom pane to separate window, and unzoom it back into it''s original location'),
('Starred GitHub repo: wfxr/tmux-fzf-url - 🚀 Quickly open urls on your terminal screen!'),
('Starred GitHub repo: All-Hands-AI/OpenHands - 🙌 OpenHands: Code Less, Make More'),
('Starred GitHub repo: frankroeder/parrot.nvim - parrot.nvim 🦜 - the plugin that brings stochastic parrots to Neovim. This is a gp.nvim-fork focused on simplicity.'),
('Starred GitHub repo: developersdigest/llm-answer-engine - Build a Perplexity-Inspired Answer Engine Using Next.js, Groq, Llama-3, Langchain, OpenAI, Upstash, Brave & Serper'),
('Starred GitHub repo: shadowfax92/Fyin - Open source alternative to Perplexity AI with ability to run locally'),
('Starred GitHub repo: relari-ai/continuous-eval - Data-Driven Evaluation for LLM-Powered Applications'),
('Starred GitHub repo: rashadphz/farfalle - 🔍 AI search engine - self-host with local or cloud LLMs'),
('Starred GitHub repo: mtkennerly/ludusavi - Backup tool for PC game saves'),
('Starred GitHub repo: rails/solid_queue - Database-backed Active Job backend'),
('Starred GitHub repo: algora-io/tv - Open source Twitch for developers'),
('Starred GitHub repo: joshuavial/aider.nvim - null'),
('Starred GitHub repo: will-moss/isaiah - Self-hostable clone of lazydocker for the web. Manage your Docker fleet with ease'),
('Starred GitHub repo: Donkie/Spoolman - Keep track of your inventory of 3D-printer filament spools.'),
('Starred GitHub repo: Shopify/tophat - Easily install and test mobile applications with a single click.'),
('Starred GitHub repo: lukasz-madon/awesome-remote-job - A curated list of awesome remote jobs and resources. Inspired by https://github.com/vinta/awesome-python'),
('Starred GitHub repo: ax-llm/ax - The unofficial DSPy framework. Build LLM powered Agents and "Agentic workflows" based on the Stanford DSP paper.'),
('Starred GitHub repo: type-challenges/type-challenges - Collection of TypeScript type challenges with online judge'),
('Starred GitHub repo: colinhacks/zod - TypeScript-first schema validation with static type inference'),
('Starred GitHub repo: psteinroe/supabase-to-zod - Generate Zod schemas (v3) from Typescript types generated by the Supabase CLI.'),
('Starred GitHub repo: ciscoheat/sveltekit-superforms - Making SvelteKit forms a pleasure to use!'),
('Starred GitHub repo: postgresml/pgcat - PostgreSQL pooler with sharding, load balancing and failover support.'),
('Starred GitHub repo: postgresml/korvus - Korvus is a search SDK that unifies the entire RAG pipeline in a single database query. Built on top of Postgres with bindings for Python, JavaScript, Rust and C.'),
('Starred GitHub repo: jla524/fromthetensor - From the Tensor to Stable Diffusion, a rough outline for a 9 week course.'),
('Starred GitHub repo: sumn2u/annotate-lab - Annotate-lab is an open-source image annotation tool for efficient dataset creation. With an intuitive interface and flexible export options, it streamlines your machine learning workflow. 🖼️✏️📑');
