#!/bin/bash

# Check if migration name is provided
if [ $# -eq 0 ]; then
  echo "Error: Migration name argument is required"
  echo "Usage: $0 <migration_name>"
  exit 1
fi

# Use the provided migration name
migration_name=$1

atlas migrate diff "$migration_name" --dev-url "docker+postgres://jumski/postgres-15-pgmq:latest/postgres" --to "file://supabase/schemas/" --dir "file://supabase/migrations"
