#!/bin/bash
# Tag matches Supabase Postgres version we align extensions with
# See: https://github.com/supabase/postgres/releases
SUPABASE_VERSION="17.6.1.054"

docker build \
  -t jumski/atlas-postgres-pgflow:${SUPABASE_VERSION} \
  -t jumski/atlas-postgres-pgflow:latest \
  --file atlas/Dockerfile atlas/
