build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN"

test-job1:
  stage: test
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  script:
    - echo "This job tests something else but it takes longer"
    - sleep 5

deploy-prod:
  stage: deploy
  script:
    - echo "Deploying $CI_COMMIT_BRANCH to production"
  environment: production
