# fly.toml app configuration file generated for educational-law-qa-misty-water-2637 on 2024-01-15T23:41:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "edulaw-ai-backend"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  max_machines_running = 1
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1280
