name: 'Setup pgflow workspace'
description: 'Common setup steps for pgflow CI workflow (run after checkout)'

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: '10.20.0'
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'
        cache-dependency-path: |
          **/pnpm-lock.yaml

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Rebuild packages that need postinstall (onlyBuiltDependencies)
      shell: bash
      run: pnpm rebuild supabase sharp
