name: 'Setup pgflow workspace'
description: 'Common setup steps for pgflow CI workflow (run after checkout)'

inputs:
  github-token:
    description: 'GitHub token for API requests (used by sqruff)'
    required: true
  atlas-cloud-token:
    description: 'Atlas Cloud token for schema management'
    required: true

runs:
  using: 'composite'
  steps:
    # Configure Docker daemon to allow containers to set high ulimits
    # This prevents "ulimit: open files: cannot modify limit: Operation not permitted" errors
    # when Supabase containers (pooler, realtime) try to set RLIMIT_NOFILE to 100000.
    # The error occurs because GitHub Actions runners have restrictive ulimit defaults
    # that prevent containers from increasing their file descriptor limits.
    # See: https://github.com/orgs/supabase/discussions/18228
    - name: Configure Docker ulimits for Supabase
      shell: bash
      run: |
        sudo mkdir -p /etc/docker
        echo '{"default-ulimits":{"nofile":{"Name":"nofile","Hard":100000,"Soft":100000}}}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - uses: pnpm/action-setup@v4
      with:
        version: '10.20.0'
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'pnpm'
        cache-dependency-path: |
          **/pnpm-lock.yaml
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline

    - name: Rebuild packages that need postinstall (onlyBuiltDependencies)
      shell: bash
      run: pnpm rebuild supabase sharp

    # Deno setup
    - uses: denoland/setup-deno@v2
      with:
        deno-version: '2.1.4'

    # Sqruff SQL linter
    - uses: ./.github/actions/setup-sqruff
      with:
        github-token: ${{ inputs.github-token }}

    # Atlas schema management
    - uses: ariga/setup-atlas@master
      with:
        cloud-token: ${{ inputs.atlas-cloud-token }}
