stages:
  - deploy

default:
  image: python:3.11-slim

.rule/main-branch-only:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.dependency/flyctl:
  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh
    - export FLYCTL_INSTALL="/root/.fly"
    - export PATH="$FLYCTL_INSTALL/bin:$PATH"

.pkg-changed/edulaw-ai-backend:
  rules:
    - changes:
        - pkgs/edulaw-ai-backend/**/*

deploy-prod/edulaw-ai-backend:
  extends:
    - .rule/main-branch-only
    - .pkg-changed/edulaw-ai-backend
    - .dependency/flyctl
  stage: deploy
  script:
    - cd pkgs/edulaw-ai-backend
    - flyctl deploy
    - curl -H "Content-Type: application/json"  -X POST  -d '{"content": "Deployed **edulaw-ai-backend** to **production**"}' "https://discord.com/api/webhooks/1225425316571254844/7OLRvm5wJlACBKqcuG0pw2TRcokZt-ZNlAaLDTX4A2NTgJPQ4rBDL78NNCvzOSJm7CYO"
  environment: production
