stages:
  - deploy

default:
  image: python:3.11-slim

deploy-prod/edulaw-ai-backend:
  stage: deploy

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - pkgs/edulaw-ai-backend/**/*

  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh
    - export FLYCTL_INSTALL="/root/.fly"
    - export PATH="$FLYCTL_INSTALL/bin:$PATH"

  variables:
    DISCORD_MESSAGE: "Deployed **edulaw-ai-backend** to **production**"
  script:
    - cd pkgs/edulaw-ai-backend
    - flyctl deploy
    - |
      curl -H "Content-Type: application/json" \
        -X POST \
        -d "{\"content\": \"$DISCORD_MESSAGE\"}" \
        $DISCORD_WEBHOOK
  environment: production
