stages:
  - deploy

default:
  image: python:3.11-slim

.rule/main-branch-only:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.dependency/flyctl:
  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh

.pkg-changed/edulaw-ai-backend:
  rules:
    - changes:
        - pkgs/edulaw-ai-backend/**/*

deploy-prod/edulaw-ai-backend:
  extends:
    # - .rule/main-branch-only
    # - .pkg-changed/edulaw-ai-backend
    - .dependency/flyctl
  stage: deploy
  script:
    - /root/.fly/bin/flyctl deploy
  environment: production
