graph TD
  fetchArticle[fetchArticle] --> summarize[summarize]
  fetchArticle --> extractKeywords[extractKeywords]
  fetchArticle --> generateImage[generateImage]
  summarize --> publish[publish]
  extractKeywords --> publish
  generateImage --> publish
