[build]
  command = "next build"          # ↙ still required by plugin if you run netlify build locally
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"