[build]
  base = "examples/playground"   # chdir before anything else (monorepo support)
  command = "next build"
  publish = ".next"              # plugin will copy everything to .netlify

[build.environment]
  NODE_VERSION = "20.18.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"