[build]
  command = "next build"          # will be ignored because you're pre-building
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"