[build]
  base = "examples/playground"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--force" # Force npm to install packages even if there are conflicts
  NODE_VERSION = "20.18.1"