project_id = "core"

[db]
port = 50422
shadow_port = 50420
major_version = 15

# disable unused features
[db.seed]
enabled = true
sql_paths = [
  "seed.sql",
]

[realtime]
enabled = true

##################################################################
# disabled services ##############################################
##################################################################

[api]
port = 50421
enabled = false
[db.pooler]
enabled = false
[edge_runtime]
enabled = false
[studio]
port = 50323
enabled = false
[inbucket]
enabled = false
[analytics]
enabled = false
[storage]
enabled = false
[auth]
enabled = false
