export const TAGLINES = [
	'Lazy storage, smart retrieval',
	'Effortless hoarding, instant recall',
	'Lazy hoarding, smart exploring',
	'Effortless hoarding for digital pack-rats',
	'Lazy now, brilliant later',
	'Hoard now, sort never',
	'Save it all, find anything',
	'Busy brain? Save the strain',
	'Save now, think never',
	'Brainless bookmarking at its finest',
	'Lazy saving for smart people',
	'Dump it, forget it, find it',
	'No tags, no problem',
	'Mindless saving, genius retrieval',
	'Hoard smarter, not harder',
	'Your digital attic, organized automatically',
	'Effortless archiving for the masses',
	'Save everything, stress about nothing',
	'Declutter your mind, not apps',
	'Thoughtless saving, priceless recall',
	'Forget organization, remember everything',
	'Save first, ask questions later',
	'Brainless bookmarking for busy minds',
	'Dump data, retrieve gold',
	'No thinking, just linking',
	'Mindless saving, magical finding',
	'Lazy archiving for overachievers',
	'Your second brain on autopilot',
	'Effortless memory, endless discovery',
	'Save without lifting a finger',
	'Thoughtless storage, brilliant recall',
	'Lazy filing, smart retrieving',
	'Forget tagging, remember living',
	'Effortless collecting, instant accessing',
	'Brainless saving, genius searching',
	'Dump knowledge, retrieve wisdom',
	'No effort required, results guaranteed',
	'Mindless archiving, mindful discovery',
	'Hoard effortlessly, find effortlessly',
	'Your digital memory, perfectly organized',
	'Effortless input, incredible output',
	'Save without thinking, find everything',
	'Thoughtless collecting, thoughtful retrieving',
	'Lazy saving, brilliant recalling',
	'Forget effort, remember content',
	'Save it and leave it',
	'Effortless dumping, smart pumping',
	'Brainless storing, genius exploring',
	'Dump data, discover treasures',
	'No work saving, all play finding',
	'Mindless input, mindblowing output'
];

export function randomTagline() {
	return TAGLINES[Math.floor(Math.random() * TAGLINES.length)];
}
