#!/bin/bash

# get env vars from supabase status and eval them for usage
supabase_env=$(supabase status --output env 2>/dev/null)

if [ $? -eq 0 ]; then
  eval "$supabase_env"
fi

if [ -f ".env" ]; then
  source .env
fi

function_name="$1"
data="$2"

curl \
  --request POST \
  "${API_URL}/functions/v1/${function_name}" \
  --header 'Authorization: Bearer '${ANON_KEY}'' \
  --header 'Content-Type: application/json' \
  --data-raw "$data"
